server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/OrderDb?useSSL=false&serverTimezone=UTC
    username: root
    password: praise22
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER_SERVICE
  config:
    import: configserver:http://localhost:9296




#eureka:
#      instance:
#      client:
#        fetch-registry: true
#        register-with-eureka: true
#        service-url:
#          defaultZone:  ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#

#  config:
#    import: configserver:http://localhost:9296
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-1558796.okta.com/oath2/default)
#      client:
#        registration:
#          internal-client:
#            provider: okta
#            authorizationGrantType: client_credentials
#            scope:  internal
#            clientId:
#            clientSecret:
#        provider:
#          okta:
#            issuerUri: https://dev-1558796.okta.com/oath2/default)
#
#



